version: '3.8'
services:
  movies:
    image: suyashay/movies:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3
  train:
    image: suyashay/train:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3
  dth:
    image: suyashay/dth:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3
  recharge:
    image: suyashay/recharge:latest
    ports:
      - "84:80"
    deploy:
      replicas: 3
